version: 2
updates:
  # Gradle
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 15
    target-branch: main
    reviewers:
      - spicelang/intellij-extension-team
    assignees:
      - spicelang/intellij-extension-team

  # Github Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    target-branch: main
    reviewers:
      - spicelang/intellij-extension-team
    assignees:
      - spicelang/intellij-extension-team