# Workflow for Java CI debug build
name: Java CI

on:
  push:
  pull_request:
    branches:
      - main
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Gradle build
        run: ./gradlew buildPlugin